name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - Feature_1
      - Feature_2
      - Feature_3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout the branch that triggered the workflow
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up Node.js (if needed for building your project)
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '14'

      # Install dependencies (if you have a build process)
      # - name: Install dependencies
      #   run: npm install

      # Build your project if needed
      # - name: Build the project
      #   run: npm run build

      # Deploy to GitHub Pages using `peaceiris/actions-gh-pages`
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${GITHUB_REF}  # The branch where the pages will be deployed
          folder: ./ # The folder to deploy (adjust based on your project structure)
          
          # Conditional feature flag approach based on the branch
          commit_message: "Deploy ${{ github.ref }} to GitHub Pages"
          
      # Example feature flag deployment: deploy different content based on branch
      # You can set up specific conditions, like editing the index.html file based on the feature flag
      # This part is optional based on your actual use case (i.e., a feature flag within your index.html)
      - name: Customize feature flag (optional step)
        run: |
          if [[ "${GITHUB_REF##*/}" == "Feature_1" ]]; then
            echo "Deploying Feature_1"
            # Add your specific changes for Feature_1
            # e.g., sed -i 's/flag_placeholder/Feature_1_enabled/' index.html
          elif [[ "${GITHUB_REF##*/}" == "Feature_2" ]]; then
            echo "Deploying Feature_2"
            # Add your specific changes for Feature_2
            # e.g., sed -i 's/flag_placeholder/Feature_2_enabled/' index.html
          elif [[ "${GITHUB_REF##*/}" == "Feature_3" ]]; then
            echo "Deploying Feature_3"
            # Add your specific changes for Feature_3
            # e.g., sed -i 's/flag_placeholder/Feature_3_enabled/' index.html
          else
            echo "Deploying Main"
          fi

