name: Deploy to GitHub Pages with Feature Flags

on:
  push:
    branches:
      - main
      - Feature_1
      - Feature_2
      - Feature_3

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Feature_1' || github.ref == 'refs/heads/Feature_2' || github.ref == 'refs/heads/Feature_3' || github.ref == 'refs/heads/main'

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main
        folder: ./  # Make sure the folder path is the root if you're deploying directly from root
        token: ${{ secrets.GH_TOKEN }}

    - name: Clean up and set feature flag (optional)
      run: |
        echo "Setting feature flag for branch ${GITHUB_REF}"
        echo "Feature flag deployed: ${GITHUB_REF}" > ./index.html
