name: Deploy to GitHub Pages with Feature Flags

on:
  push:
    branches:
      - main
      - Feature_1
      - Feature_2
      - Feature_3

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Feature_1' || github.ref == 'refs/heads/Feature_2' || github.ref == 'refs/heads/Feature_3' || github.ref == 'refs/heads/main'

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Git configuration
      run: |
        git config user.name "kishangupta1216"
        git config user.email "guptakishan1216@gmail.com"

    - name: Initialize gh-pages branch (if not exists)
      run: |
        git fetch origin gh-pages || git checkout --orphan gh-pages  # Create the gh-pages branch if it doesn't exist
        git reset --hard  # Reset to ensure no uncommitted changes
        git clean -fd  # Clean up any untracked files

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ./ # Make sure this is the folder generated by the build process
        token: ${{ secrets.GH_TOKEN }}

    - name: Clean up and set feature flag (optional)
      run: |
        echo "Setting feature flag for branch ${GITHUB_REF}"
        echo "Feature flag deployed: ${GITHUB_REF}" > ./index.html
